In [21]:
import numpy as np

In [6]:
b = np.array([1,2,3]) #1D tensor

In [ ]:
b

In [8]:
b.ndim

1

In [12]:
arr1 = np.array([[1,2],[3,4]])

In [13]:
arr1.ndim #2D Tensor

2

In [15]:
arr1.shape

(2, 2)

In [16]:
len(arr1.shape)

2

In [18]:
x =np.array([[1,2,3],
            [4,5,6]])

In [19]:
print("Shape: ",x.shape)
print("Rank: ",x.ndim)
print("number of axes: ",x.ndim)

Shape:  (2, 3)
Rank:  2
number of axes:  2


In [20]:
x.ndim    # Rank / number of axes
x.shape   # Size of each axis

(2, 3)

using data we perform tensor


In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("students.csv")

In [24]:
data = df.to_numpy()

In [25]:
print(data)

[[101  85  78  90  20]
 [102  72  88  76  21]
 [103  91  95  89  20]
 [104  65  70  72  22]
 [105  88  82  85  21]
 [106  76  91  80  20]
 [107  95  89  94  22]
 [108  69  75  68  21]]


In [27]:
print("Rank : ",data.ndim)
print("shape: ",data.shape)

Rank :  2
shape:  (8, 5)
